### ISSUE TITLE
Reloading is not working

### ISSUE THREAD

**Issue by crud-boy** [wking-io/elm-live#179]
Elm is installed using exe, elm-live is compiled and started normally, but the change of src/main.elm cannot be detected.

dir
```
|src
|--Main.elm
|custom.html
```
Main.elm
```
import Browser exposing (..)
import Browser.Navigation as Nav
import Html exposing (..)

type alias Model =
  {

  }


type Msg
  = Pass

init: flags -> (Model, Cmd msg)
init _ = 
  (Model, Cmd.none)


view: Model -> Html msg
view model =
  div [] [ text "hello" ]


update: Msg -> Model -> (Model, Cmd msg)
update msg model =
  (model, Cmd.none)


subscriptions: model -> Sub msg
subscriptions model =
  Sub.none


main: Program () Model Msg
main =
  element 
  { init = init
  , view = view
  , update = update
  , subscriptions = subscriptions
  }


```
custom.html
```
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="UTF-8">
  <title>Main</title>
  <script src="dist/elm.js"></script>
</head>

<body>
  <div id="elm"></div>
  <script>
  var app = Elm.Main.init({
    node: document.getElementById('elm')
  });
  </script>
</body>
</html>
```

run cmd
```
elm-live src/Main.elm --open --start-page=custom.html -- --output=dist/elm.js
or
elm-live src/Main.elm --hot --start-page=custom.html -- --output=dist/elm.js
```

output
```
Success! Compiled 1 module.

elm-live:
  The build has succeeded. Starting the server! We’ll open your app
  in the default browser as soon as it’s up and running.


Reload web server:
  - Website URL: http://localhost:8000
  - Listening on port: 8000
  - Monitoring dir: C:\Users\vsq_k\Desktop\FootballMonitorUI

elm-live:
  Watching src\**\*.elm.
```

**Comment by wking-io** [comment]
Hmm okay I know what it going on. Tried to fix it, but must have missed something. Issue is with Glob patterns using back slashes on windows

**Comment by wking-io** [comment]
Should be fixed in most recent release! Let me know if it isn't!

**Comment by crud-boy** [comment]
Not only has it not been repaired, but there are also a lot of errors, which seem to be file permissions on Linux system, and no windows.

```powershell
PS C:\Users\vsq_k\Desktop\FootballMonitorUI - ELM> elm-live  src/Main.elm --hot  --start-page=custom.html -- --output=elm.jselm-live:
  Hot Reloading is ON

  Warning: Hot Reloading does not replay the messages of the app.
  It just restores the previous state and can lead to bad state.
  If this happen, reload the app in the browser manually to fix it.


elm-live:
  Server has been started! Server details below:
    - Website URL: http://localhost:8000
    - Serving files from: C:\Users\vsq_k\Desktop\FootballMonitorUI - ELM


elm-live:
  The build has succeeded.

elm-live:
  Watching the following files:
    - src/**/*.elm

(node:18832) UnhandledPromiseRejectionWarning: TypeError: Cannot mix BigInt and other types, use explicit conversions    at FSWatcher._hasReadPermissions (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\chokidar\index.js:755:36)
    at ReaddirpStream.filterPath [as _fileFilter] (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\chokidar\index.js:680:12)    at ReaddirpStream._isFileAndMatchesFilter (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\readdirp\index.js:234:31)
    at ReaddirpStream._exploreDirectory (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\readdirp\index.js:163:23)    at async ReaddirpStream._read (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\readdirp\index.js:122:7)
(node:18832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.    


```

**Comment by wking-io** [comment]
Looks like that is a known issue with the new version of the file watcher elm-live uses: `chokidar` 

https://github.com/paulmillr/chokidar/issues/871#issuecomment-519758433

I will revert to an older version to get this working 👌

**Comment by crud-boy** [comment]
Update to chokidar 3.0.2, reload function is normal

**Comment by crud-boy** [comment]
New problem, code updates too fast to cause compilation errors
```powershell
elm-live:
  You’ve changed `src\Main.elm`. Rebuilding!

elm-live:

-- CORRUPT BINARY --------------- C:\Users\vsq_k\Desktop\FootballMonitorUI - ELM\elm-stuff\0.19.0\Main.elmo


The binary data at C:\Users\vsq_k\Desktop\FootballMonitorUI -
ELM\elm-stuff\0.19.0\Main.elmo is corrupt.

Elm caches build artifacts in the following directories:

    C:\Users\vsq_k\AppData\Roaming\elm
    elm-stuff/

Maybe you recently installed a command line tool or editor plugin that messes
with them? They definitely should not be doing that, but you never know! So
maybe try deleting them? Everything will be rebuilt from scratch. This may help
reveal the corrupting influence.


Terminal will be reused by tasks, press any key to close it.
```

**Comment by wking-io** [comment]
@crud-boy could you test it now?

As for that second error try deleting your `elm-stuff` and making sure that `elm-live` is finding the right version of `elm make`. Sometimes if you have an older version loaded globally it will cause issues

**Comment by crud-boy** [comment]
```powershell
> Executing task: elm-live src/Main.elm --hot --port=8001 -- --output=dist/elm.js <


elm-live:
  Hot Reloading is ON

  Warning: Hot Reloading does not replay the messages of the app.  
  It just restores the previous state and can lead to bad state.   
  If this happen, reload the app in the browser manually to fix it.


elm-live:
  Server has been started! Server details below:
    - Website URL: http://localhost:8001
    - Serving files from: C:\Users\vsq_k\Desktop\FootballMonitorUI - ELM
  

elm-live:
  The build has succeeded. 

elm-live:
  Watching the following files:
    - src/**/*.elm

internal/fs/utils.js:426
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined        
    at readFile (fs.js:302:10)
    at C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\crocks\Async\index.js:54:10
    at Object.fork (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\crocks\Async\index.js:155:20)
    at C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\crocks\Async\index.js:254:41
    at settle (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\crocks\Async\index.js:151:16)
    at ReadFileContext.callback (C:\Users\vsq_k\AppData\Roaming\npm\node_modules\elm-live\node_modules\crocks\Async\index.js:56:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:246:13)
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
```

**Comment by wking-io** [comment]
@crud-boy I cannot replicate these issues are you still having trouble with any of them? Hoping to move to beta soon and these are the only issues still reported

**Comment by sukkergris** [comment]
The actual issue for the error above - is the missing `--dir' flag when using the `--output` flag.
This is the faulty line:
> Executing task: elm-live src/Main.elm --hot --port=8001 -- --output=dist/elm.js <

This is the corrected line:
> Executing task: elm-live src/Main.elm --hot -**-dir=dist** --port=8001 -- --output=dist/elm.js <

I'm personally not getting my changes picked up. (Running in devcontainer)
