### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by davidg88007** [wking-io/elm-live#200]
When trying to run the sample from [Front End Masters, Intro to Elm v2](https://frontendmasters.com/courses/intro-elm)

```
david (master *) part1 $ ls
elm.js  elm.json  elm-stuff  index.html  Main.elm  README.md
david (master *) part1 $ elm-live Main.elm --open -- --output=elm.js
/home/david/.nvm/versions/node/v8.2.1/lib/node_modules/elm-live/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/david/.nvm/versions/node/v8.2.1/lib/node_modules/elm-live/node_modules/ws/index.js:3:19)
david (master *) part1 $ 

```

**Comment by sli** [comment]
Based on your nvm path, you're using a version of Node that doesn't support the spread operator on objects. Update it to a more recent version -- at least v8.6 -- and it should be fixed.
