### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by logisin** [wking-io/elm-live#201]
elm-live post-app/Main.elm --pushstate -- --output=elm.js

elm-live:
  Server has been started! Server details below:
    - Website URL: http://localhost:8000
    - Serving files from: C:\Users\other\beginning-elm

Error parsing result:  SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (C:\Users\other\AppData\Roaming\npm\node_modules\elm-live\lib\src\build.js:110:33)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (C:\Users\other\AppData\Roaming\npm\node_modules\elm-live\node_modules\cross-spawn\lib\enoent.js:40:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
{ build:
   { action: 'error',
     data:
      'elm: not enough bytes\nCallStack (from HasCallStack):\n  error, called at libraries\\binary\\src\\Data\\Binary.hs:212:21 in binary-0.8.5.1:Data.Binary\n' },
  cwd: 'C:\\Users\\other\\beginning-elm',
  dir: 'C:\\Users\\other\\beginning-elm',
  elm: 'elm',
  elmArgs: [ 'post-app/Main.elm', '--output=elm.js' ],
  getAction: [Function: getAction],
  host: 'localhost',
  hot: false,
  log: [Function: bound consoleCall],
  open: false,
  port: 8000,
  proxyPrefix: false,
  proxyHost: false,
  pushstate: true,
  reload: true,
  server:
   Server {
     _events:
      [Object: null prototype] {
        request: [Function],
        connection: [Function: connectionListener],
        listening: [Function: bound emit],
        error: [Function: bound emit],
        upgrade: [Function: upgrade] },
     _eventsCount: 5,
     _maxListeners: undefined,
     _connections: 0,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: true,
     pauseOnConnect: false,
     httpAllowHalfOpen: false,
     timeout: 120000,
     keepAliveTimeout: 5000,
     maxHeadersCount: null,
     headersTimeout: 40000,
     _connectionKey: '4:127.0.0.1:8000',
     [Symbol(IncomingMessage)]: { [Function: IncomingMessage] super_: [Function] },
     [Symbol(ServerResponse)]: { [Function: ServerResponse] super_: [Function] },
     [Symbol(asyncId)]: 14,
     [Symbol(kUsedByWebSocketServer)]: true },
  useServer: true,
  ssl: false,
  startPage: 'index.html',
  target: 'elm.js',
  verbose: false }

**Comment by logisin** [comment]
With Elm 0.19.1 the error changes to:
C:\Users\other\AppData\Roaming\npm\node_modules\elm-live\lib\src\build.js:103
      reject(errorMsg(model.elm, error, model.recover))
             ^

TypeError: errorMsg is not a function
    at ChildProcess.<anonymous> (C:\Users\other\AppData\Roaming\npm\node_modules\elm-live\lib\src\build.js:103:14)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.cp.emit (C:\Users\other\AppData\Roaming\npm\node_modules\elm-live\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
