### ISSUE TITLE
TypeError at startup (WSL)

### ISSUE THREAD

**Issue by sullyj3** [wking-io/elm-live#203]
```
❯ elm-live src/App.elm                                                                                         2s 695msevents.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.createServer (http.js:34:10)
    at model (/home/james/.node/lib/node_modules/elm-live/lib/src/start.js:259:75)
    at /home/james/.node/lib/node_modules/elm-live/node_modules/crocks/core/compose.js:8:14
    at settle (/home/james/.node/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:151:16)
    at /home/james/.node/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:27:62
    at fork (/home/james/.node/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:155:20)
    at /home/james/.node/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:224:16
```

**Comment by epfahl** [comment]
Anything on this? Running Elm 0.19.1.

**Comment by eniac314** [comment]
upgrading node to the latest stable version fixed it for me.
https://stackoverflow.com/questions/24068035/node-js-https-createserver-throws-typeerror-listener-must-be-a-function
