### ISSUE TITLE
exception when running elm-live

### ISSUE THREAD

**Issue by angusdavisadobe** [wking-io/elm-live#221]
When running elm-live with latest version, I get an exception:
node --version
v8.9.4

elm --version
0.19.1

elm-live --version
4.0.2

elm-live src/Picshare.elm --open
events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:265:10)
    at Object.createServer (http.js:34:10)
    at model (/usr/local/lib/node_modules/elm-live/lib/src/start.js:259:75)
    at /usr/local/lib/node_modules/elm-live/node_modules/crocks/core/compose.js:8:14
    at settle (/usr/local/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:151:16)
    at /usr/local/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:27:62
    at fork (/usr/local/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:155:20)
    at /usr/local/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:224:16

**Comment by angusdavisadobe** [comment]
sorry. found a similar issue already raised. As suggested, upgrading to latest node.js fixed the problem.
