### ISSUE TITLE
elm-live crash when a file is not found instead responding with a 404

### ISSUE THREAD

**Issue by lucamug** [wking-io/elm-live#235]
If you try an url for a non existing file, for example: http://localhost:8000/xyz/index.html

elm-live will stop with  the error:

```
internal/fs/utils.js:537
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (fs.js:313:10)
    at /Users/userName/projectName/node_modules/crocks/Async/index.js:54:10
    at Object.fork (/Users/userName/projectName/node_modules/crocks/Async/index.js:155:20)
    at /Users/userName/projectName/node_modules/crocks/Async/index.js:254:41
    at settle (/Users/userName/projectName/node_modules/crocks/Async/index.js:151:16)
    at ReadFileContext.callback (/Users/userName/projectName/node_modules/crocks/Async/index.js:56:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13) {
  code: 'ERR_INVALID_ARG_TYPE'
}
node /Users/userName/projectName/elm-start/src-js/start.js serverDev exited with code 0
```

Could be related to

https://github.com/wking-io/elm-live/issues/207
https://github.com/wking-io/elm-live/issues/205
https://github.com/wking-io/elm-live/issues/195

**Comment by francisdb** [comment]
I can confirm this issue. I saw it after checking a fresh repo and freshly installing elm-live. I guess it was trying to load the index before it was fully built

```
git:(master) elm-live src/Main.elm --open

elm-live:
  Server has been started! Server details below:
    - Website URL: http://localhost:8000
    - Serving files from: /Users/foo/xxx/glmorph


internal/fs/utils.js:535
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at readFile (fs.js:313:10)
    at /Users/foo/.nvm/versions/node/v12.16.3/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:54:10
    at Object.fork (/Users/foo/.nvm/versions/node/v12.16.3/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:155:20)
    at /Users/foo/.nvm/versions/node/v12.16.3/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:254:41
    at settle (/Users/foo/.nvm/versions/node/v12.16.3/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:151:16)
    at ReadFileContext.callback (/Users/foo/.nvm/versions/node/v12.16.3/lib/node_modules/elm-live/node_modules/crocks/Async/index.js:56:47)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by erlandsona** [comment]
Anyone have a fork with this fixed? Been dealing with this same issue as well.

**Comment by lucamug** [comment]
> Anyone have a fork with this fixed? Been dealing with this same issue as well.

At work we use `elm-go`, a clone that we made to fix some issues of `elm-live`

**Comment by helldorado** [comment]
This occurs when the `index.html` file is missing from the `--dir`

**Comment by Natim** [comment]
The minimum `index.html` file should look like this:

```
<html>
<body>
  <div id="app"></div>
  <script src="app.js"></script>
  <script>
    const element = document.getElementById("app");
    const app = Elm.YOUR_APP.init({
        node: element,
        flags: {}
    });
  </script>
</body>
</html>
```
